name: jappeos_login
description: A login screen for JappeOS.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  provider: ^6.0.5
  
  jappeos_desktop_ui:
    git:
      url: https://github.com/Jappe-OS/JappeOS-DesktopUI.git
      ref: master

  shade_theming:
    git:
      url: https://github.com/Jappe-OS/ShadeTheming.git
      ref: master

  jappeos_core_lib:
    git:
      url: https://github.com/Jappe-OS/JappeOS-CoreLib.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - resources/images/backgrounds/